### ISSUE TITLE
How safe is this to be used in production?

### ISSUE THREAD

**Issue by jEnbuska** [joshwnj/react-visibility-sensor#104]
I haven't heard any of my colleges using this library so I'm wondering how safe is this to be used in production?
I have a table with about ~10 000 rows and with using this library I seem to be able to show only few hundred rows at a time. I have tried using react-virtualize but It too buggy.

**Comment by roopemerikukka** [comment]
We have used this in production to create infinite scroll effect to load more posts. You can of course try it first in your dev/staging environment and if it works, then just lock the version and you are good to go :)

**Comment by nirpeled** [comment]
I use it in production and it's pretty awesome. And yeah, as @roopemerikukka suggested - always lock the version (to any npm package that you use) and you're good.

**Comment by joshwnj** [comment]
Thanks everyone for your input on this.
