### ISSUE TITLE
Don't wrap the children

### ISSUE THREAD

**Issue by gaearon** [joshwnj/react-visibility-sensor#12]
Is there any real need to wrap the children in a `div`?
`React.findDOMNode` will work just fine even if you just return `this.props.children` from `render`.

For extra safety, you can return `React.Children.only(this.props.children)`. This will force the consumer to supply a single child (which is the DOM node that will be tracked).

**Comment by joshwnj** [comment]
Thanks for the PR, closing this now that it's merged
