### ISSUE TITLE
Visibility is not sensed in new Chrome Version 69.0.3497.92 (Official Build) snap (64-bit)

### ISSUE THREAD

**Issue by agentmilindu** [joshwnj/react-visibility-sensor#132]
I have a Facebook-like notification dropdown which uses React Visibility Sensor to mark the notifications as read. 
After I upgraded the Chrome to the latest version it no longer works. It works on other browsers, I tried on Firefox and Safari.

It always sense as `visible=false` on new Chrome.

**Comment by joshwnj** [comment]
Thanks for reporting @agentmilindu . Could you please take a look and see what is different in your case from this demo? https://codesandbox.io/s/p73kyx9zpm

If you are able to share a codesandbox that reproduces the bug, that would be even better.

**Comment by romandubrov** [comment]
actually "general usage" example from Docs does not work
```
return (
  <VisibilitySensor onChange={onChange} />
);
```
this is never fired for me

However, if you wrap your elements in VisibilitySensor, it works like a charm
```
return (
  <VisibilitySensor onChange={onChange}>
    <MyContent/>
  </VisibilitySensor>
);
```

I suggest @joshwnj mention this in docs

**Comment by joshwnj** [comment]
@romandubrov you're right - it's because that example doesn't have any "size", so it is not considered visible. This was introduced recently and we forgot to update the readme :) https://github.com/joshwnj/react-visibility-sensor/pull/114

I've updated the readme in #133
