### ISSUE TITLE
How to keep elements visible after first scroll

### ISSUE THREAD

**Issue by danihazler** [joshwnj/react-visibility-sensor#168]
Hi there,

Using react-visibility-sensor I've created a higher component to animate the sections of my project on scroll.

I'm having problems trying to make it work only on the first scroll. At the moment the sections appear and disappear.

```import VisibilitySensor from 'react-visibility-sensor';

export const SlideUp = ({ children }) => {
  const [isVisible, setVisibility] = useState(false);

  const onChange = visiblity => {
    setVisibility(visiblity);
  };

  return (
    <VisibilitySensor
      partialVisibility
      offset={{ top: 200 }}
      onChange={onChange}
    >
      <div
        style={{
          transition: `opacity ${0.5}s ease, transform ${0.5}s ease`,
          opacity: isVisible ? 1 : 0,
          transform: isVisible ? `translateY(${0}px)` : `translateY(${20}px)`,
        }}
      >
        {children}
      </div>
    </VisibilitySensor>
  );
};```

- use example:

<SlideUp>
  <Section />
</SlideUp>```

**Comment by ghost** [comment]
@danihazler Can you please share how you fixed that?

**Comment by danihazler** [comment]
@muhammedmagdi sure, you can see my solution here:

https://stackoverflow.com/questions/58436201/keep-elements-visible-after-first-scroll-using-react-visibility-sensor

I hope it helps

**Comment by ghost** [comment]
@danihazler Thanks for sharing. 
I have just one question about react-pose library since it says it has been deprecated in favor of this library: https://github.com/framer/motion
Do you think I can use this library instead at your solution?

**Comment by danihazler** [comment]
Oh yeah... I totally forgot about that. I need to update my solution (when I have some time).
But yeah, I'm pretty sure you can use this new library instead.
