### ISSUE TITLE
Upgrade path from v1 to v2

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/react-visibility-sensor#17]
@kof & @gaearon, continuing from #13 I'd like to get your thoughts on how to make a smooth transition. 

I like the improved transparency of assigning child DOM nodes directly, rather than passing `className` and `style` as props.  But I understand there may be more implications to the change than I've thought through.  

@kof could you please give some details about what broke in your code with the upgrade, and whether you see any other concerns or blockers to making a smooth transition?

**Comment by gaearon** [comment]
Basically the transition should be looking for all `<VisibilitySensor>`s in your code, checking if any of them has `style` or `className` attributes, and when this is the case, putting an empty `<div>` inside as its child with these attributes.

Before:

```js
<VisibilitySensor className='something' />
<VisibilitySensor style={{ color: 'red' }} />
```

After:

```js
<VisibilitySensor><div className='something'  /></VisibilitySensor>
<VisibilitySensor><div  style={{ color: 'red' }} /></VisibilitySensor>
```

**Comment by joshwnj** [comment]
Thanks for the notes @gaearon - I'll use this in a new "Migrating from v1.x" section in the readme when I get some time later today.

**Comment by kof** [comment]
Just create a changelog, this lib is not that complex.

**Comment by joshwnj** [comment]
Good call, I've added that here and will keep it updated with details of future updates: https://github.com/joshwnj/react-visibility-sensor/blob/master/CHANGELOG.md

Cheers

**Comment by kof** [comment]
thanks!
