### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by tchret** [joshwnj/react-visibility-sensor#18]
http://bower.io/ :+1:

**Comment by AntonTrollback** [comment]
+1

**Comment by kompot** [comment]
"As it currently exists, bower is bad for the JavaScript ecosystem. Plain and simple."
https://github.com/reactjs/redux/issues/944#issuecomment-154858804

I'd say that there's no reason to add bower support.

**Comment by kof** [comment]
yes, just add the link to the dist file on cdn via npm ...

**Comment by kof** [comment]
There are cdn's which use npm, you can simple install a file from cdn. This way we need to publish to npm only, cdn providers will take it from there.

**Comment by kof** [comment]
dist version should be however umd ready, current dist is not. Also dist shouldn't be under version control.

**Comment by joshwnj** [comment]
There's a section in the README to address this now: https://github.com/joshwnj/react-visibility-sensor#including-the-script-directly
