### ISSUE TITLE
Perhaps a non-commonJS dist?

### ISSUE THREAD

**Issue by digitalmaster** [joshwnj/react-visibility-sensor#20]
For those of use who work on projects that aren't using commonJS yet. Tnx.. Great project bdw!

**Comment by joshwnj** [comment]
Thanks, good suggestion. Im not a good person to answer this since I'm using commonjs for everything :) What would be the most convenient dist for you and your projects?

**Comment by digitalmaster** [comment]
I'm also not sure what the convention behind this is.. but for now i was able to get by with just a few changes.. https://github.com/digitalmaster/react-visibility-sensor/commit/b32702079179000f5fb0b9c2bc20a9a8aebb82c4

**Comment by joshwnj** [comment]
@digitalmaster we're now publishing a UMD version to npmcdn, you can see an example here: https://github.com/joshwnj/react-visibility-sensor/blob/master/example-umd/index.html#L82
