### ISSUE TITLE
Elements taller than the page can be shown as not even partially visible

### ISSUE THREAD

**Issue by acgourley** [joshwnj/react-visibility-sensor#25]
If your element is taller than the page, and it's top is above the page, and it's bottom is below the page, partialVertical can still end up as false. 

Here's the problem:

```
var partialVertical =
        (rect.top >= containmentRect.top && rect.top <= containmentRect.bottom)
     || (rect.bottom >= containmentRect.top && rect.bottom <= containmentRect.bottom);
```

I suggest adding 
`|| (rect.top <= containmentRect.top && rect.bottom >= containmentRect.bottom);`

**Comment by joshwnj** [comment]
Good find! Would you be interested in helping to put together a new test case?

**Comment by EugeneHlushko** [comment]
Guys its not on npm, please merge
