### ISSUE TITLE
feature request: more control over which sides of the viewport the sensor will watch

### ISSUE THREAD

**Issue by Ghostavio** [joshwnj/react-visibility-sensor#26]
To explain this better I'll talk about my use case: after a certain point in the page, I want to display two floating action buttons on the bottom of the page (mobile only - material design like), so for me it's only interesting to calculate the `bottom`, not all directions.

**Comment by thomaslein** [comment]
+1

**Comment by Andarist** [comment]
Check if that helps you - https://github.com/joshwnj/react-visibility-sensor/pull/42
