### ISSUE TITLE
Problem with ReactDOM.findDOMNode(this) in visibility-sensor.js

### ISSUE THREAD

**Issue by skywickenden** [joshwnj/react-visibility-sensor#27]
I had a bug which after some investigation I tracked down to the following in visibility-sensor.js

      var el = ReactDOM.findDOMNode(this);

For me this was selecting the child span in the sensor rather than the actual sensor element. This was throwing off the results from getBoundingClientRect on the next line.

I'm not familiar enough with React yet to know why the child node is being returned instead of the component node. I've read up on it and my understanding is that it should return the parent.

For now I've edited the line to be:

    var el = ReactDOM.findDOMNode(this).parentNode;

Which selects the correct element. But I would like to know why. Does anyone have any insight.

Could it be related to the sensor elements being absolutely positioned?

**Comment by kof** [comment]
Can you post your render function?

**Comment by skywickenden** [comment]
Thanks. I've worked it out. It was to do with my styles leading me to look at the wrong element.
