### ISSUE TITLE
Support 0.13 

### ISSUE THREAD

**Issue by B-Stefan** [joshwnj/react-visibility-sensor#3]
I had some problems with React 0.13 so I wrote a new class. 
(Sorry but wrote new was faster than debug)  
Maybe this will help someone: https://gist.github.com/B-Stefan/ef800cd0f8b10597d5df

**Comment by joshwnj** [comment]
This is cool, thanks! Helped me to upgrade to 0.13.1: https://github.com/joshwnj/react-visibility-sensor/blob/master/package.json#L19
