### ISSUE TITLE
Set isVisible manually via props

### ISSUE THREAD

**Issue by kof** [joshwnj/react-visibility-sensor#31]
I have a need to reset isVisible  value manually via props. The reason I need it is because I am using `active: false` option, which means auto check of visibility is disabled. The logical consequence of that is an element doesn't get a signal when its hidden and once it becomes visible again it "thinks" it is already visible and doesn't triggers the onChange callback.

I will send you a pull request in a bit.

**Comment by kof** [comment]
It's basically a performance optimization. Because I could have called .check method on every sensor and let it update the state, but in my use case, I have a list, it would mean potentially that check method would ran on a number of sensors.

I set isVisible to null instead, which means that by the next .check call, it will detect the change anyways.

**Comment by kof** [comment]
Oh, I found a better solution, isVisible over props is not nice, because its actually manipulating an internal state.

I found a way without to change react-visibility-sensor: .check() call returns the state, I can use it to manually call onChange callback, thats it.

Sorry for the issue, closing it.

**Comment by kof** [comment]
I have got another prob and I consider this as a bug: check() method returns current state, this doesn't include changes of setState() inside of .check, because it is async.

I think if setState is used, then it needs to return the new state, not the current.

**Comment by joshwnj** [comment]
@kof is this resolve in v3.0.1 or are there still outstanding issues?

**Comment by kof** [comment]
that PR is all I needed to solve my issues.
