### ISSUE TITLE
Partial visibility issue

### ISSUE THREAD

**Issue by Andarist** [joshwnj/react-visibility-sensor#35]
Scenario:

1. List of observed items and checking partial visibility with containment

2. New item added to the list -> `componentDidMount` with `active` flag so watching begins

3. as I have `partialVisibility` on I get `isVisible` and `onChange` fires

4. my custom callback depends on the second parameter as I need to check against `visibilityRect.bottom` which is `false` at the moment - my component had no chance yet to scroll down

5. my component scrolling down in its `componentDidUpdate`

6. checker checking each interval against `this.state.isVisible !== isVisible` to fire callback again and its previous run get me `true` cause of the `partialVisibility` and once again its `true` cause nothing changes

However for my use case it is a change I need to detect.

I have in my mind couple workaround for this issue, but I think this should be somehow tackled by a library and I can fix it, but aint sure what kind of fix should I apply. Any ideas @joshwnj?

**Comment by joshwnj** [comment]
@Andarist if you have a moment it would be great to add the example you described to https://github.com/joshwnj/react-visibility-sensor/tree/master/example

**Comment by Andarist** [comment]
@joshwnj

I aint sure what do you mean by adding an example. Did you just mean an example of the reproduced issue?

I think I've detailed my scenario pretty well, if not please let me know.

I had to fork your repo to make it work for my use use, here is the PR with my change - https://github.com/joshwnj/react-visibility-sensor/pull/42

**Comment by joshwnj** [comment]
Thanks @Andarist I see what you mean now. I've merged it (with a few changes necessary to bring it up to date with master) and pushed to master. Please take a look and let me know if that fixes your case, then I'll publish a new version to npm.

**Comment by Andarist** [comment]
Well, it looks good I guess. Let me know when published :)

**Comment by joshwnj** [comment]
Sorry @Andarist didn't see this until now. Published as `v3.4.0`
