### ISSUE TITLE
Reporting isVisible for free element

### ISSUE THREAD

**Issue by skovhus** [joshwnj/react-visibility-sensor#50]
For elements that do not have a size in the DOM, `react-visibility-sensor` currently reports that it is visible.

I think this should be the first check:

``` javascript
if (rect.top + rect.right + rect.bottom + rect.left + rect.width === 0) {
  isVisible = false;
}
```

**Comment by joshwnj** [comment]
@skovhus good idea, and thanks for the PR! I'll get to it soon I promise :)

**Comment by neeharv** [comment]
Awesome lib @joshwnj! Any timeframe on getting this into a release? Would be super helpful 👍

**Comment by joshwnj** [comment]
thanks @neeharv . We're nearly ready to release this, just need to do some final reviews of https://github.com/joshwnj/react-visibility-sensor/pull/51

If you're able to help by pulling that branch and making sure things still work as expected, that will speed up the process a lot :)

**Comment by ryan-foster-ck** [comment]
What's the status/future of this patch?  Anyway I can help get it across the line?
