### ISSUE TITLE
containment example

### ISSUE THREAD

**Issue by joshwnj** [joshwnj/react-visibility-sensor#7]
Hi @kof, thanks for your recent contribution. I had a go at adding this to the example page: http://joshwnj.github.io/react-visibility-sensor/ It's pretty ugly but hopefully gets the functionality across :P

When you have a moment could you please take a look and let me know if this is the way you imagined it being used?  Also let me know if you think there is anything else that would be good to demonstrate on the example page.

Thanks!

**Comment by kof** [comment]
I would remove onChange handler from render function and put it into prototype, in this case it doesn't matter but in real life it would lead to a leak.

**Comment by kof** [comment]
But yeah this example demonstrates exactly the use case.

**Comment by joshwnj** [comment]
Good tip, thanks. I've updated the example, just so I don't accidentally give anyone bad advice :)
