### ISSUE TITLE
Need help with using "offset" properly

### ISSUE THREAD

**Issue by shivekkhurana** [joshwnj/react-visibility-sensor#77]
Hi @joshwnj, community members,

Thanks for building and maintaining this package. It has turned out to be of great help !

--
In a project I'm working on, I need to track the visibility of `div`s that stay on screen. The vertical height of each div might be greater than that of the `viewport`  (window in my case), and hence I'm using : 

```js
partialVisibility={'top'} // also tried true
offset={{top: 100}} // also tried negative offset on bottom
```

What I want to achieve is if more than `k`px from the top is in the viewport, than mark it as visible. 

I've created a small widget to check the visibility in real time. And my code above doesn't seem to work. Here is the wrapper that I use over the visibility sensor : 

```js
import React from 'react';
import ReactVisibilitySensor from 'react-visibility-sensor';

class VisibilitySensor extends React.Component {
  render() {
    return (<div>
      <ReactVisibilitySensor
        onChange={this.props.onChange}
        scrollCheck={true}
        resizeCheck={true}
        scrollThrottle={100}
        intervalDelay={8000}
        partialVisibility={'top'}
        offset={{
          top: 100
        }}
      >
        {this.props.children}
      </ReactVisibilitySensor>
    </div>);
  }
}

export default VisibilitySensor;
```

And here is a screenshot of my app : 
(As you can see on the right, no page is marked visible, I want the partial page in viewport, to be marked visible)
![screen shot 2017-05-13 at 7 52 53 pm](https://cloud.githubusercontent.com/assets/1925158/26026315/a7b740d8-3816-11e7-8f3c-9016ef9498e6.png)

What am I doing wrong here ?

Thanks.

**Comment by shivekkhurana** [comment]
**Update:** 
 
I also tried using `minTopValue`, but that didn't work either.

**Comment by joshwnj** [comment]
hi @shivekkhurana sorry for the confusion here :)

The solution might be a negative value on `offset.top`. Could you please take a look here and see if it recreates the behaviour you're trying to achieve? https://codepen.io/joshwnj/pen/PjwVym

**Comment by shivekkhurana** [comment]
Yes it does. Thanks for taking time out to write this example.
